name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Copy artifacts
        run: |
          JAR_FILE=$(find target -name "*.jar" -type f | head -n 1)
          echo "$JAR_FILE"
          JAR_OUT=$(echo "$JAR_FILE" | sed -E 's/^.{7}//')
          echo "$JAR_OUT"
          echo "JAR_OUT=$JAR_OUT" >> $GITHUB_ENV
          cp "$JAR_FILE" "./$JAR_OUT"

      - name: Upload bundle
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ICDiscordSRVAddon-build
          path: ${{ env.JAR_OUT }}